version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: blog_development
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: always

  app:
    build: .
    image: myapp_image:latest 
    restart: always
    depends_on:
      - db
      - redis
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/blog_development
      REDIS_URL: redis://redis:6379/0
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_SERVE_STATIC_FILES: "true"
    volumes:
      - storage:/app/storage
    ports:
      - "3000:3000" 
    command: ["bin/rails", "server", "-b", "0.0.0.0"]

  sidekiq:
    image: myapp_image:latest 
    restart: always
    depends_on:
      - app 
      - redis
      - db
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:password@db:5432/blog_development
      REDIS_URL: redis://redis:6379/0
    volumes:
      - storage:/app/storage
    command: ["bundle", "exec", "sidekiq"]

volumes:
  postgres_data:
  storage: